baseURL: "https://wtimme.github.io/"
languageCode: "en-us"
title: "wtimme"
theme: "PaperMod"
params:
  disableThemeToggle: true
menu:
  main:
    - identifier: archives
      name: archive
      url: /archives/
      weight: 30
